"""
Centralized prompt templates for all LLM tasks.
Each prompt is designed for Gemma 4 E4B and expects structured JSON output.
"""

# ── System Prompts ───────────────────────────────────────────────────

SYSTEM_FINANCIAL_ANALYST = """You are an expert Indian stock market analyst specializing in NSE/BSE intraday and swing trading. You analyze technical indicators, news sentiment, and market context to provide precise, actionable trading insights. You focus on capital preservation and risk management. Always respond with structured JSON as requested. Be concise and data-driven."""

SYSTEM_MARKET_ANALYST = """You are a senior market strategist covering the Indian equity markets (NSE/BSE). You analyze broad market conditions including Nifty 50, Sensex, India VIX, sector rotation, FII/DII flows, and global cues to provide a comprehensive daily market outlook. Always respond with structured JSON as requested."""


# ── Sentiment Analysis ───────────────────────────────────────────────

SENTIMENT_ANALYSIS_PROMPT = """Analyze the following news headlines for {ticker} ({company_name}) and provide a structured sentiment assessment.

Headlines:
{headlines}

Analyze each headline for:
1. Overall sentiment toward the stock price
2. Key events that could impact trading (earnings, mergers, regulatory actions, etc.)
3. Risk flags that traders should be aware of

Respond with ONLY this JSON structure:
{{
    "overall_sentiment": "strongly_positive" | "positive" | "neutral" | "negative" | "strongly_negative",
    "sentiment_score": <float from -1.0 to 1.0>,
    "reasoning": "<1-2 sentence explanation of the sentiment>",
    "key_events": ["<event1>", "<event2>"],
    "risk_flags": ["<risk1>", "<risk2>"],
    "trading_impact": "bullish" | "neutral" | "bearish",
    "confidence": <float from 0.0 to 1.0, how confident you are in this assessment>
}}"""


# ── Signal Validation ────────────────────────────────────────────────

SIGNAL_VALIDATION_PROMPT = """You are validating a trade signal generated by a rule-based strategy engine. Review the full context and provide your assessment.

TRADE SIGNAL:
- Ticker: {ticker}
- Direction: {direction}
- Entry Price: ₹{entry_price}
- Stop-Loss: ₹{stop_loss}
- Target: ₹{target}
- Risk-Reward: {risk_reward}:1
- Strategy Confidence: {confidence}/100
- Reasons (Pros): {reasons}
- Risks (Cons): {cons}

TECHNICAL SNAPSHOT:
- Trend: {trend}
- RSI (14): {rsi}
- MACD Histogram: {macd_histogram}
- Volume Ratio: {volume_ratio}x avg
- Volatility Regime: {volatility_regime}
- ADX: {adx}
- Stochastic K/D: {stoch_k}/{stoch_d}

NEWS SENTIMENT:
{news_context}

MARKET CONTEXT:
{market_context}

PAST MISTAKES WITH THIS TICKER:
{mistake_history}

Validate this trade considering ALL the above context. Consider:
1. Is the technical setup genuinely strong or are there hidden weaknesses?
2. Does the news environment support or contradict this trade?
3. Is the broader market favorable for this type of trade today?
4. Have we made similar mistakes with this ticker before?

Respond with ONLY this JSON:
{{
    "verdict": "strong_buy" | "buy" | "hold" | "avoid",
    "adjusted_confidence": <int 0-100, your recommended confidence>,
    "reasoning": "<2-3 sentences explaining your verdict>",
    "key_risk": "<the single biggest risk for this trade>",
    "conviction_level": "high" | "medium" | "low"
}}"""


# ── Mistake Analysis ─────────────────────────────────────────────────

MISTAKE_ANALYSIS_PROMPT = """Analyze this losing trade and explain what went wrong. Provide actionable lessons.

TRADE DETAILS:
- Ticker: {ticker}
- Direction: {direction}
- Entry: ₹{entry_price} on {entry_date}
- Exit: ₹{exit_price} on {exit_date} (Reason: {exit_reason})
- P&L: ₹{pnl} ({pnl_pct}%)
- Stop-Loss was: ₹{stop_loss}

TECHNICAL STATE AT ENTRY:
{technical_snapshot}

NEWS AROUND THE TRADE:
{news_context}

MARKET CONDITIONS:
{market_context}

RULE-BASED FAILURE CODES: {rule_based_codes}

Provide a deep analysis:
1. What was the primary cause of this loss?
2. Were there warning signs that were missed?
3. What should have been done differently?
4. What pattern should the system learn to avoid?

Respond with ONLY this JSON:
{{
    "primary_cause": "<concise explanation of what went wrong>",
    "missed_signals": ["<signal1>", "<signal2>"],
    "lesson_learned": "<actionable lesson for future trades>",
    "pattern_to_avoid": "<describe the setup pattern to avoid>",
    "severity": "minor" | "moderate" | "major",
    "sector_context": "<was this a sector-wide or stock-specific issue?>"
}}"""


# ── Market Briefing ──────────────────────────────────────────────────

MARKET_BRIEFING_PROMPT = """Generate a comprehensive morning market briefing for Indian equity markets (NSE/BSE) trading today.

MARKET DATA:
- Nifty 50: {nifty_value} ({nifty_change})
- Sensex: {sensex_value} ({sensex_change})
- India VIX: {vix_value} ({vix_regime})
- Nifty above EMA50: {nifty_above_ema50}
- Nifty above EMA200: {nifty_above_ema200}

SECTOR PERFORMANCE (1-day):
{sector_performance}

TOP MARKET HEADLINES:
{market_headlines}

GLOBAL CUES:
{global_cues}

Provide a structured market briefing that helps an intraday trader plan their day:

Respond with ONLY this JSON:
{{
    "market_mood": "strongly_bullish" | "bullish" | "neutral" | "bearish" | "strongly_bearish",
    "mood_score": <float from -1.0 to 1.0>,
    "summary": "<3-4 sentence market overview>",
    "sector_outlook": {{
        "hot_sectors": ["<sector1>", "<sector2>"],
        "cold_sectors": ["<sector1>", "<sector2>"],
        "rotation_insight": "<1 sentence on sector rotation>"
    }},
    "key_levels": {{
        "nifty_support": <float>,
        "nifty_resistance": <float>,
        "comment": "<1 sentence on key levels>"
    }},
    "risk_factors": ["<risk1>", "<risk2>"],
    "trading_advice": "<2-3 sentences of practical advice for today>",
    "confidence": <float 0.0-1.0>
}}"""
